#!/bin/bash

mamba create -n env_cwl -c conda-forge cwltool nodejs 

mamba create -c conda-forge -p /srv/conda/envs/env_crop  gdal click pystac 
mamba create -c conda-forge -p /srv/conda/envs/env_norm_diff click gdal  
mamba create -c conda-forge -p /srv/conda/envs/env_otsu gdal scikit-image click 
mamba create -c conda-forge -p /srv/conda/envs/env_stac click pystac python=3.9 pip && \
    /srv/conda/envs/env_stac/bin/pip install rio_stac
